### ISSUE TITLE
"get" should be "aws" in "Deploying to AWS" page 

### ISSUE THREAD

**Issue by tmintz** [pushkin-consortium/pushkin#106]
I think there's a typo after the section on installing the ECS CLI. The commands for obtaining the keys are given as:
```
$ get configure get aws_access_key_id --profile [profile]
$ get configure get aws_secret_access_key --profile [profile]
```
but I believe it should be
```
$ aws configure get aws_access_key_id --profile [profile]
$ aws configure get aws_secret_access_key --profile [profile]
```
(Mac users who installed aws system-wide will have to prefix "sudo" to the commands)

**Comment by parkerrobbins** [comment]
@tmintz, thank you for reporting this!

@jkhartshorne, @conbainbridge fixed this yesterday via commit [40135be](https://github.com/pushkin-consortium/pushkin/commit/40135be2ca941630310c7ff1ab3d275373ca68ab).
