### ISSUE TITLE
[AWS Deployment] Does the ECS CLI need to be configured?

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin#116]
I'm a bit confused [here](https://languagelearninglab.gitbook.io/pushkin/getting-started/deploying-to-aws):

![ecs_configure](https://user-images.githubusercontent.com/31826170/89664695-8d4c1b00-d8a5-11ea-8b01-9279677f9884.png)

It says that the ECS CLI does not need to be configured, but then the next line says "In configuring the ECS CLI". I'm wondering if this is a mistake or if this is part of a stage that has not yet been documented.

**Comment by jkhartshorne** [comment]
@parkerrobbins I believe you are correct. Fixing now.
