### ISSUE TITLE
Worked example for lexical decision template

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#119]
I think that users would benefit from a simple worked example of using each of the experiment templates. That is, an example of a complete config.js and a complete stim.js that gives rise to some specific experiment. Just so it's all more concrete.

**Comment by parkerrobbins** [comment]
@jkhartshorne What would you like that is different from what comes by default?

Here's the default `config.js` and `stim.js` that comes with the lexical decision experiment:

`config.js`
```javascript
// Custom stylin'

var experimentConfig = {
    fontColor: "black",
    fontSize: "18px",
    fontFamily: "'Open Sans', 'Arial', sans-serif",
    correctiveFeedback: "true"
}

export default experimentConfig;
```

`stim.js`
```javascript
// Example stimuli

const stimArray = [
    { word_1: 'SOCKS', word_2: 'SHOE', both_words: true, related: true },
    { word_1: 'SLOW', word_2: 'FAST', both_words: true, related: true },
    { word_1: 'QUEEN', word_2: 'KING', both_words: true, related: true },
    { word_1: 'LEAF', word_2: 'TREE', both_words: true, related: true },

    { word_1: 'SOCKS', word_2: 'TREE', both_words: true, related: false },
    { word_1: 'SLOW', word_2: 'SHOE', both_words: true, related: false },
    { word_1: 'QUEEN', word_2: 'FAST', both_words: true, related: false },
    { word_1: 'LEAF', word_2: 'KING', both_words: true, related: false },

    { word_1: 'AGAIN', word_2: 'PLAW', both_words: false, related: false },
    { word_1: 'BOARD', word_2: 'TRUDE', both_words: false, related: false },
    { word_1: 'LIBE', word_2: 'HAIR', both_words: false, related: false },
    { word_1: 'MOCKET', word_2: 'MEET', both_words: false, related: false },

    { word_1: 'FLAFF', word_2: 'PLAW', both_words: false, related: false },
    { word_1: 'BALT', word_2: 'TRUDE', both_words: false, related: false },
    { word_1: 'LIBE', word_2: 'NUNE', both_words: false, related: false },
    { word_1: 'MOCKET', word_2: 'FULLOW', both_words: false, related: false }
]

export default stimArray;
```

**Comment by jkhartshorne** [comment]
Basically, explaining exactly what you would change in order to make the experiment do something different. (Doesn't really matter exactly what "different" is.)

This is obvious to you and me, but that's because we are used to standard patterns in how programming works. Imagine someone who is very new to programming. They'll benefit from having a very specific example.

**Comment by parkerrobbins** [comment]
@jkhartshorne Is this what you were looking for? I might also consider putting the example in a separate document, but I haven't thought of a logical file structure yet.

**Comment by jkhartshorne** [comment]
@parkerrobbins - this is perfect. Thanks!
