### ISSUE TITLE
[AWS EC2 users] 'Local' testing of experiment using basic site template breaks because Pushkin doesn't know my IP address

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin#158]
@jkhartshorne I mentioned this yesterday, but figured it would be better recorded here.

When I install the basic site template and basic experiment, run `pushkin prep` and `pushkin start;`, the site loads, but the experiment won't load because it's still looking to `localhost` instead of the IP address of the EC2 instance.

![image](https://user-images.githubusercontent.com/31826170/91577844-52269000-e917-11ea-9593-e52d84c3d71a.png)

**Comment by parkerrobbins** [comment]
@jkhartshorne Curiously, when doing _true_ local testing on my Ubuntu machine, it doesn't matter whether I use `localhost` or my machine's local IP address when using the basic site template. Not sure how that's possible.

**Comment by jkhartshorne** [comment]
Can you please check the migration instructions against your
implementation. Is there anything in your code that doesn't match the
migration instructions?

**Comment by parkerrobbins** [comment]
This was a fresh install. But yes, let me check.

**Comment by parkerrobbins** [comment]
No difference. Maybe the solution is to edit pushkin.yaml and replace `localhost` with the IP address of the EC2 instance? Because AWS EC2 users are not actually accessing `localhost`.

**Comment by parkerrobbins** [comment]
Update: That is not the solution. Replacing `localhost` with the IP address of my instance in `pushkin.yaml` breaks `pushkin prep` even after doing `pushkin kill`. Bummer.

**Comment by jkhartshorne** [comment]
Huh. Have we ever gotten 'local' testing to work on AWS? I thought we had. Do you think you can figure out which version that was with?

**Comment by parkerrobbins** [comment]
It's hard to say because the auth0 error was getting in our way after Firefox updated and no longer allowed the connection (like Chrome, others). I do think we got this to work. I can dig a little bit on Monday to see when that was.

**Comment by jkhartshorne** [comment]
Yes, please let me know. I'm trying to decide if we keep trying to fix this, or simply give up (at least temporarily) on "local" testing via AWS.

**Comment by parkerrobbins** [comment]
@jkhartshorne Closing as local testing with WSL works fine (see changes in #167 and #168).
