### ISSUE TITLE
aws profile

### ISSUE THREAD

**Issue by gepping** [pushkin-consortium/pushkin#172]
Hi all,

When I run `pushkin aws init`, I keep entering an aws profile name that results in: `The config profile (____) could not be found`.  How do I go about finding the IAM user that is configured on my AWS CLI?

**Comment by gepping** [comment]
I've tried the username from the new_user_credential file that I downloaded when I was configuring AWS CLI and that did not work, nor did my actual AWS account name.

**Comment by gepping** [comment]
Turns out it was just "default"

**Comment by restmegan** [comment]
Hi @gepping ! Yeah it's usually just "default" since the aws credentials are stored as the default user. We will add a note in the documentation to clarify this. Glad you figured it out!
