### ISSUE TITLE
Problem starting Docker

### ISSUE THREAD

**Issue by gepping** [pushkin-consortium/pushkin#173]
Hi all,
Sorry, but I've got another issue that I'm hoping to get some help with.

I've been able to run `pushkin start` and view my stub website in the past, but when I ran `pushkin start` a couple of days ago I kept getting an error message that had to do with yarn.  Unfortunately, I did not save this original message.  To try to get around this, I tried uninstalling and reinstalling yarn, but this did not fix the problem.

Then, I used `pushkin armageddon`.  Afterward, I got an error message on `pushkin prep` that seemed to imply the issue was with either yarn or docker.  

So, I uninstalled and reinstalled both yarn and docker and now I can't get docker to start properly.  When I run, `sudo dockerd`, I get a long message that ends with:
```
WARN[2020-10-22T17:22:16.428903600-04:00] could not use snapshotter devmapper in metadata plugin  error="devmapper not configured"                                                                                                              INFO[2020-10-22T17:22:16.428927300-04:00] metadata content store policy set             policy=shared                   failed to start containerd: timeout waiting for containerd to start  
```

I seem to be going in the wrong direction, so I would appreciate any help.  Thanks!

**Comment by jkhartshorne** [comment]
I'm not sure. I'm not really an expert on docker. Can you describe the exact steps you went through to delete and reinstall docker?

**Comment by gepping** [comment]
Hi @jkhartshorne , I was actually just trying to figure out how to delete the post.  Turns out there was a file the stopped docker-ce from deleting and I had to remove that file myself.  I've currently got `pushkin aws init` running so hopefully I'll be able to see my deployed website in a couple of minutes.  Thank you!
