### ISSUE TITLE
Add command to documentation for Ubuntu version checking

### ISSUE THREAD

**Issue by hzeng2** [pushkin-consortium/pushkin#188]
Since it is recommended for Windows users to use certain versions of Ubuntu, it would be helpful to add a step in installation, to check the version: my suggestion is, in [this step](https://languagelearninglab.gitbook.io/pushkin/getting-started/installing-pushkin-and-dependencies/windows-10/windows-install#:~:text=WSL%202%20and-,installed%20Ubuntu,-%2C%20you%20will%20probably) of the Pushkin website, add a command ```lsb_release -a``` in Ubuntu terminal, which will print out the version of Ubuntu that the users are using.

**Comment by jkhartshorne** [comment]
@hzeng2 -- can you please open a pull request with this change?
