### ISSUE TITLE
Update recommended Ubuntu versions on Pushkin website

### ISSUE THREAD

**Issue by hzeng2** [pushkin-consortium/pushkin#189]
Since Ubuntu 18.04 is reaching its [end of standard support](https://wiki.ubuntu.com/Releases) in April 2023, it is necessary that we update the recommended versions of Ubuntu on [Pushkin website](https://languagelearninglab.gitbook.io/pushkin/getting-started/installing-pushkin-and-dependencies/windows-10/windows-install#:~:text=We%20recommend%20using-,Ubuntu%2018.04,-or%2020.04.).

**Comment by jkhartshorne** [comment]
@hzeng2 -- can you please open a pull request with this change?
