### ISSUE TITLE
Slight change of installation arrangement on Pushkin website (for Windows)

### ISSUE THREAD

**Issue by hzeng2** [pushkin-consortium/pushkin#190]
Although the installation page indicates that users should go to another page to finish installation, it might be worth emphasizing this mandatory step by putting it at the beginning of the page. For example, following [this sentence](https://languagelearninglab.gitbook.io/pushkin/getting-started/installing-pushkin-and-dependencies/windows-10/windows-install#:~:text=Start%20here%20to%20build%20install%20Pushkin%20and%20its%20dependencies%20on%20Windows%2010.), add 
>", then continue to [Ubuntu Linux](https://languagelearninglab.gitbook.io/pushkin/getting-started/installing-pushkin-and-dependencies/ubuntu-install) to finish installation."

**Comment by jkhartshorne** [comment]
@hzeng2 -- can you just go ahead and do a pull request for the documentation that implements this?
