### ISSUE TITLE
Add new line characters when configuring `.bashrc` (for Windows and Ubuntu)

### ISSUE THREAD

**Issue by hzeng2** [pushkin-consortium/pushkin#191]
When users are not accustomed to adding a new line character at the end of `.bashrc` every time they edit the file, and they forget to add a new line character the next time before they append new content to `.bashrc`, it could lead to errors that are hard to trace. Therefore, it would be helpful and time-saving to add a new line character `\n` at both the beginning and the end when (and anytime in the future when) appending to `.bashrc`. Therefore, [these commands](https://languagelearninglab.gitbook.io/pushkin/getting-started/installing-pushkin-and-dependencies/ubuntu-install#:~:text=%24%20yarn%20config,source%20~/.bashrc) could be modified as:
```
yarn config set prefix ~/.yarn   
echo -e '\nexport PATH="$PATH:`yarn global bin`"\n' >> ~/.bashrc
source ~/.bashrc
```

**Comment by jkhartshorne** [comment]
@hzeng2 can you please go ahead and implement?

**Comment by hzeng2** [comment]
@jkhartshorne -- I have made the pull request. Also I made a gif of the updated commands in action. 

![haozeng_DESKTOP-VSKNB7K_-_-2023-06-16-22-44-45](https://github.com/pushkin-consortium/pushkin/assets/90575813/0ba4ec69-1c5a-4c1e-9f47-78a66d98015a)

Please let me know if I should replace the [current gif](https://github.com/pushkin-consortium/pushkin/blob/master/docs-gitbook/.gitbook/assets/ubuntu4%20%281%29.gif) with this new one. After that I will assign reviewers of this pull request. Thanks!
