### ISSUE TITLE
Can't reach localhost site after successful `pushkin prep` and `pushkin start` (for Windows)

### ISSUE THREAD

**Issue by hzeng2** [pushkin-consortium/pushkin#192]
I got
```
Set up databases successfully
 Database updated. Shutting down...
```
after running `pushkin prep`,
and
```
Successfully tagged pushkin_server:latest
 Starting. You may not be able to load localhost for a minute or two.
```
after running `pushkin start`. And they are similar to the example outputs, [here](https://languagelearninglab.gitbook.io/pushkin/getting-started/quickstart/sample_output#example-output-for-pushkin-prep) and [here](https://languagelearninglab.gitbook.io/pushkin/getting-started/quickstart/sample_output#example-output-for-pushkin-start).

However, I cannot reach localhost site to view the experiment.

**Comment by svanhedger** [comment]
+1 to this issue. I've followed the tutorial using WSL2 / Ubuntu 20.04, WSL2 / Ubuntu 18.04 on two separate machines, with both showing the expected output and then not loading the localhost site. Thinking it might have to do with an unavailable port or some firewall settings, I tried the tutorial via AWS EC2 (Ubuntu 18.04). All steps ran smoothly and as expected, but when completing 'pushkin start' the site (public ipv4) refused the connection, even after waiting over 20 minutes. Given that the output is identical to the tutorial, it has made troubelshooting quite difficult, so any help would be greatly appreciated!

**Comment by jkhartshorne** [comment]
Possibly related to https://github.com/pushkin-consortium/pushkin/issues/187

**Comment by jkhartshorne** [comment]
Also see https://github.com/pushkin-consortium/pushkin/issues/193 for perhaps partial solution. Though it uses npx and we're using yarn.

**Comment by jkhartshorne** [comment]
@hzeng2 if https://github.com/pushkin-consortium/pushkin-sitetemplate-basic/pull/1 solves this problem for you, please close.
