### ISSUE TITLE
Conditional timelines not working in the most recent Pushkin version

### ISSUE THREAD

**Issue by ellissc** [pushkin-consortium/pushkin#198]
Following the instructions on JsPsych (https://www.jspsych.org/7.0/overview/timeline/#conditional-timelines), conditional timelines do not work in Pushkin. It seems that the `on_finish` function does not fire after a given trial is completed, not sure if it is a version issue or due to the way that timelines are handled in Pushkin.

**Comment by jessestorbeck** [comment]
I think this is probably resolved with the latest releases of the experiment template upgrading to jsPsych7. We're in the process of rebuilding some of the old experiment templates, which should confirm this.

**Comment by jessestorbeck** [comment]
@ellissc I've confirmed that conditional timelines and on_finish work in v5.0.1 of the basic experiment template.

**Comment by jkhartshorne** [comment]
Actually should work as part of the upgrade to jsPsych 7: https://github.com/pushkin-consortium/pushkin-exptemplates-basic/releases/tag/v5.0.0

(@jessestorbeck -- it's good practice to link directly to the commit or version that fixes the problem. This makes it easier to track what fixed what.)

**Comment by ellissc** [comment]
Great, thank you!
