### ISSUE TITLE
Copying terminal commands from documentation includes `$` characters

### ISSUE THREAD

**Issue by jodeleeuw** [pushkin-consortium/pushkin#214]
Using the built-in copy button, e.g., here....

![image](https://github.com/pushkin-consortium/pushkin/assets/595524/ef748b85-6f01-4eea-aa70-b7405334427d)

... copies the text `$ pushkin install experiment`, which includes the `$`. Pasting this into the terminal doesn't work.

**Comment by Halogen7A** [comment]
I will be removing the dollar signs
