### ISSUE TITLE
`Pushkin prep` password authentication failure

### ISSUE THREAD

**Issue by ayang21** [pushkin-consortium/pushkin#219]
After following the steps of starting a Pushkin experiment and running `pushkin prep`, we receive this error:

> Waiting for database to start...
> { stdout: '', stderr: '' }
> Waiting for test db...
> Building test_web from /home/haozeng/pushkin_quickstart/experiments/test/web page
> Building test_api from /home/haozeng/pushkin_quickstart/experiments/test/api controllers
> test_api is built
> test_web is built
> test_api is published locally via yalc
> test_web is published locally via yalc
> Loaded web page for test (test_web)
> Added test to experiments.js
> Writing out experiments.js
> Installing combined API
> Installed combined API
> Installing combined front-end
> Installed combined front-end
> {
>   stdout: 'pushkin_test_db_1 Up 2 seconds (health: starting)\n',
>   stderr: ''
> }
> Waiting for test db...
> {
>   stdout: 'pushkin_test_db_1 Up 7 seconds (health: starting)\n',
>   stderr: ''
> }
> Waiting for test db...
> {
>   stdout: 'pushkin_test_db_1 Up 11 seconds (health: starting)\n',
>   stderr: ''
> }
> Waiting for test db...
> { stdout: 'pushkin_test_db_1 Up 15 seconds (healthy)\n', stderr: '' }
> Waiting for test db...
> starting migrations....
> db: localtestdb
> {
>   localtestdb: {
>     user: 'postgres',
>     pass: 'example',
>     url: 'localhost',
>     port: '5432',
>     name: 'test_db',
>     host: 'test_db'
>   },
>   localtransactiondb: {
>     user: 'postgres',
>     pass: 'example',
>     host: 'test_transaction_db',
>     port: '5433',
>     url: 'localhost',
>     name: 'test_transaction_db'
>   }
> }
> Waiting for transaction database to start...
> Waiting for test transaction db...
> Ran migrations for localtestdb
> Running seeds on /home/haozeng/pushkin_quickstart/experiments/test
> Set up localtestdb successfully
> Waiting for test transaction db...
> Waiting for test transaction db...
>  Main database updated. Shutting down...
> Waiting for test transaction db...
> Waiting for test transaction db...
> Waiting for test transaction db...
> Waiting for test transaction db...
> Waiting for test transaction db...
> Starting migrations for test transactions DB.
> starting migrations....
> db: localtransactiondb
> {
>   localtestdb: {
>     user: 'postgres',
>     pass: 'example',
>     url: 'localhost',
>     port: '5432',
>     name: 'test_db',
>     host: 'test_db'
>   },
>   localtransactiondb: {
>     user: 'postgres',
>     pass: 'example',
>     host: 'test_transaction_db',
>     port: '5433',
>     url: 'localhost',
>     name: 'test_transaction_db'
>   }
> }
> _Problem running migrations.
> Failed to set up databases:
>         error: password authentication failed for user "postgres"
> /home/haozeng/.config/yarn/global/node_modules/pg-protocol/dist/parser.js:287
>         const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);_
>                                                                                                  ^
> 
> error: password authentication failed for user "postgres"
>     at Parser.parseErrorMessage (/home/haozeng/.config/yarn/global/node_modules/pg-protocol/dist/parser.js:287:98)
>     at Parser.handlePacket (/home/haozeng/.config/yarn/global/node_modules/pg-protocol/dist/parser.js:126:29)
>     at Parser.parse (/home/haozeng/.config/yarn/global/node_modules/pg-protocol/dist/parser.js:39:38)
>     at Socket.<anonymous> (/home/haozeng/.config/yarn/global/node_modules/pg-protocol/dist/index.js:11:42)
>     at Socket.emit (node:events:511:28)
>     at addChunk (node:internal/streams/readable:332:12)
>     at readableAddChunk (node:internal/streams/readable:305:9)
>     at Readable.push (node:internal/streams/readable:242:10)
>     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
>   length: 104,
>   severity: 'FATAL',
>   code: '28P01',
>   detail: undefined,
>   hint: undefined,
>   position: undefined,
>   internalPosition: undefined,
>   internalQuery: undefined,
>   where: undefined,
>   schema: undefined,
>   table: undefined,
>   column: undefined,
>   dataType: undefined,
>   constraint: undefined,
>   file: 'auth.c',
>   line: '326',
>   routine: 'auth_failed'
> }**
> 
> Node.js v20.2.0

Stating that the password failed for the user 'postgres'.

**Comment by jkhartshorne** [comment]
@ayang21 -- have you gotten this again? My guess is that you had a left-over database from something else, and that `pushkin armageddon` will fix the issue.

**Comment by jkhartshorne** [comment]
@ayang21 confirmed that he can log in using pgAdmin, so the database is there and works. He is investigating what could cause this sort of problem.

**Comment by jkhartshorne** [comment]
@ayang21 -- is this problem still live?

**Comment by jkhartshorne** [comment]
@ayang21 ??

**Comment by ayang21** [comment]
This error no longer persists. But I do not know what fixed Pushkin Prep with the password authentication. I think the update to the new CLI might have fixed it. That, or you restart the pushkin_quickstart and begin with a new slate
