### ISSUE TITLE
Figure out how to version documentation

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#228]
So we probably want old versions of the documentation to remain available, since people may be using old versions. This will increasingly be the case as more people are using pushkin.

This will require some planning, since there's a question of how we do the versioning, given that we have repos with various versions of their own. It may be worth reading up on mono-repos, which I think maybe address this issue? @jodeleeuw has been using them.

**Comment by jodeleeuw** [comment]
FWIW we use [mike](https://github.com/jimporter/mike) for versioning our docs. We currently version docs for releases of jspsych core but not for plugins. We use [changesets](https://github.com/changesets/changesets) to manage versioning of packages in our monorepos, which also handles automated changelogs.

**Comment by jkhartshorne** [comment]
@ayang21 @jessestorbeck -- can you look into this and put together an issue template?

**Comment by hunterschep** [comment]
I am going to close this issue with this comment, as we are now fully set up and using mike to version our docs which are live [here](https://pushkin-consortium.github.io/pushkin/3.6/)
