### ISSUE TITLE
request returned Internal server Error

### ISSUE THREAD

**Issue by ayang21** [pushkin-consortium/pushkin#229]
Versions:
Pushkin-cli@3.2.0
Docker@24.0.4

![image](https://github.com/pushkin-consortium/pushkin/assets/109900818/83ffd526-d427-414b-a980-dcf91ad908d3)

There seems to be an issue with Docker where, despite it actively running, it cannot be logged in with the corresponding security credentials due to some sort of API request error.

**Comment by jkhartshorne** [comment]
Looks like that's not a Pushkin issue, right? This is the docker CLI that is failing. I'd google that specific error. Are you sure your local dockerhub credentials are correct? 

Take a look at [this](https://github.com/docker/desktop-linux/issues/156).

**Comment by jkhartshorne** [comment]
Also, can you try the other two testing computers?

**Comment by ayang21** [comment]
I seemed to have fixed some problems by completely restarting my computer, but now I am reaching this error: 
![image](https://github.com/pushkin-consortium/pushkin/assets/109900818/25f5c438-cbc6-41d7-943c-2b44596ce1e1)

**Comment by jkhartshorne** [comment]
Did you leave out some of the output?

Also, can you tell me where `experiments.js` currently is?

On August 3, 2023, Sebastian Waz ***@***.***> wrote:
> I seemed to have fixed some problems by completely restarting my
> computer, but now I am reaching this error:
>  
>

>  
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pushkin-
> consortium/pushkin/issues/229#issuecomment-1664481845>, or unsubscribe
> <https://github.com/notifications/unsubscribe-
> auth/ABOVVYY7BOW7GMSPSUQLCL3XTPYOPANCNFSM6AAAAAA3DDSRTI>.
> You are receiving this because you commented.Message ID: <pushkin-
> ***@***.***>
>


--
Sent with HEY <https://hey.com/sent>

**Comment by ayang21** [comment]
That was all of the message. The bottom green part is the shell waiting for the next command. 

experiments.js comes from @jessestorbeck's JsPsych 7 lexical decision template since I am using the lexical decision experiment template which was cloned into my folder, and is outside the pushkin_quickstart folder. I had already ran `pushkin install experiment` on that folder through PATH

**Comment by jkhartshorne** [comment]
experiments.js is created by pushkin-cli and should not be in the
lexical decision template. Can you tell me the exact location? 

J

On August 3, 2023, Sebastian Waz ***@***.***> wrote:
> That was all of the message. The bottom green part is the shell
> waiting for the next command.
>
> experiments.js comes from @jessestorbeck
> <https://github.com/jessestorbeck>'s JsPsych 7 lexical decision
> template since I am using the lexical decision experiment template
> which was cloned into my folder, and is outside the pushkin_quickstart
> folder. I had already ran pushkin install experiment on that folder
> through PATH
>

—
Reply to this email directly, view it on GitHub
<https://github.com/pushkin-consortium/pushkin/issues/229#issuecomment-
1664489868>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABOVVY4WIEUJKC3ADVAJHBTXTPZJTANCNFSM6AAAAAA3DDSRTI>.
You are receiving this because you commented.Message ID: <pushkin-
***@***.***>


--
Sent with HEY <https://hey.com/sent>

**Comment by ayang21** [comment]
There is one in `\home\ayang25\pushkin_quick\pushkin\front-end\src` and `\home\ayang25\pushkin_quick\pushkin\front-end`

**Comment by jkhartshorne** [comment]
I think this might be related to this: https://github.com/pushkin-consortium/pushkin/issues/230

Can you try the things suggested there and see if it helps?

**Comment by jkhartshorne** [comment]
@ayang21 -- bumping this.

**Comment by jkhartshorne** [comment]
@ayang21 -- bumping again.

**Comment by ayang21** [comment]
After restarting the project and beginning from a clean slate, ```docker login``` worked as intended
