### ISSUE TITLE
X64 warning

### ISSUE THREAD

**Issue by Halogen7A** [pushkin-consortium/pushkin#230]
![image](https://github.com/pushkin-consortium/pushkin/assets/91691805/b1429af3-3a38-4162-adf9-98bcbbeab1f2)

The images for the experiments show an X64 warning. These experiments mostly showed errors during the ` pushkin prep ` stage, so it might be due to that.

**Comment by jkhartshorne** [comment]
@Halogen7A -- I just pushed an update to the `multi-platform-docker-images` branch of the CLI, as well as updates to the `multiplatform` branch of `pushkin-exptemplates-basic` and the `FixAWS` branch of `pushkin-sitetemplates-basic`. Please try using through up through `pushkin start` and tell me if a) the warnings go away, and b) if you run into any issues.

**Comment by Halogen7A** [comment]
@jkhartshorne I will give that a try today. Thank you.

**Comment by Halogen7A** [comment]
I encountered this error during pushkin prep.

![image](https://github.com/pushkin-consortium/pushkin/assets/91691805/50f8505d-fd94-4c84-b228-47304ce52628)

However, I do not get any warnings from Docker.

![image](https://github.com/pushkin-consortium/pushkin/assets/91691805/6fd24a83-715c-4ea0-8bf4-56ba464d0610)

**Comment by jkhartshorne** [comment]
Well, that must is good. Can you show me the containers?

**Comment by jkhartshorne** [comment]
Latest error seems to have been a one-off.
