### ISSUE TITLE
docs issue: setSaveAfterEveryStimulus

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#237]
This function is now deprecated. We recommend using:

```
    const jsPsych = initJsPsych({
      ...,
      on_data_update: (data) => pushkin.saveStimulusResponse(data),
    });
```

where the `...` is any other specifications the user wants to make. 

Please update the docs.

**Comment by jkhartshorne** [comment]
@jessestorbeck -- I don't think this is a huge hurry, so I'm happy to let this wait until Adam is back.

**Comment by ayang21** [comment]
@jkhartshorne @jessestorbeck I just created a pull request to update this.

**Comment by jessestorbeck** [comment]
@ayang21 -- Thanks. I made a few edits before merging.
