### ISSUE TITLE
Pushkin not found 

### ISSUE THREAD

**Issue by ayang21** [pushkin-consortium/pushkin#239]
<img width="374" alt="image" src="https://github.com/pushkin-consortium/pushkin/assets/109900818/43cee06f-ebe4-4355-b4de-75433c3953bd">
I was previously getting the error above after trying to run a simple pushkin command where it stated that pushkin would not be recognized even after running `yarn global add pushkin-cli`. I even tried to do reinstall node@20.2.0 and then continuing my process from there.

**Comment by ayang21** [comment]
In order to fix this issue, I had to install node@20.5.0 and then running `npm install --global yarn`. Everything after this was normal and pushkin commands run smoothly, but I'm interested in seeing how the new node version interacts with pushkin.

**Comment by jessestorbeck** [comment]
@ayang21, have you tried using [nvm](https://www.freecodecamp.org/news/node-version-manager-nvm-install-guide/)?

**Comment by ayang21** [comment]
Yeah I did. The issue was fixed. I just wondered if anyone knows about any other problems have occurred with node versions with Pushkin
