### ISSUE TITLE
CodeSpaces for windows machines 

### ISSUE THREAD

**Issue by hunterschep** [pushkin-consortium/pushkin#248]
Pushkin currently is not functional for windows users, could github codespaces be a useful alternative for windows?

**Comment by jkhartshorne** [comment]
Some notes based on current conversations:

- Codespaces is not free. So it would be ideal for people to be able to do development locally and *testing* on codespaces. So we are thinking of trying to make sure `install` runs locally. However, `prep` and `start` and `aws` and the to-be-created `update` should be run in codespaces. And people can always just buy a unix machine if they find that annoying :)

**Comment by jessestorbeck** [comment]
Codespaces documentation added in #286
