### ISSUE TITLE
Docs: Improve explanations of pushkin repos in getPushkin.rst

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#28]

**Comment by jessestorbeck** [comment]
Maybe it's a good idea to add some description of pushkin-consortium repos near the beginning of the docs?

**Comment by jkhartshorne** [comment]
Good idea! Assigning to you for now, but you can sub-assign to either of the others.

**Comment by jkhartshorne** [comment]
Right now there's already some information [here](https://languagelearninglab.gitbook.io/pushkin/developers/developing-with-pushkin), though it's out-of-date since it mentions pushkin-jspsych.
