### ISSUE TITLE
Docs: Explain how to update a pushkin installation

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#29]

**Comment by parkerrobbins** [comment]
Is this referring to [this](https://languagelearninglab.gitbook.io/pushkin/getting-started/quickstart#updating) in the Quickstart? If so, I think we may need further explanation as we have not yet heard anything about `docker-compose` or `start test_db`.

**Comment by jessestorbeck** [comment]
This seems to be covered in the docs [here](https://languagelearninglab.gitbook.io/pushkin/advanced/pushkin-cli#update).
