### ISSUE TITLE
Suppressing "completed" branches

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#321]
@jessestorbeck so for instance `welcome-workflow` is fully integrated into `main`. But it's still floating around. Is there a good way to get rid of it?

**Comment by hunterschep** [comment]
If it is fully integrated into main, it can be deleted on the local and remote

**Comment by jessestorbeck** [comment]
I deleted some old branches from [here](https://github.com/pushkin-consortium/pushkin/branches/all). There's one very old branch that has an unmerged commit with some potentially useful info: https://github.com/pushkin-consortium/pushkin/commit/d4547e2154450815945bdd2ba7a9e34a84d07ffe

**Comment by jkhartshorne** [comment]
Looks like there's documentation for unit tests. I guess check to see if
it matches the current unit tests?

Is there anything else?

On April 2, 2024, Sebastian Waz ***@***.***> wrote:
> I deleted some old branches from here <https://github.com/pushkin-
> consortium/pushkin/branches/all>. There's one very old branch that has
> an unmerged commit with some potentially useful info: d4547e2
> <https://github.com/pushkin-
> consortium/pushkin/commit/d4547e2154450815945bdd2ba7a9e34a84d07ffe>
>

—
Reply to this email directly, view it on GitHub
<https://github.com/pushkin-consortium/pushkin/issues/321#issuecomment-
2032156213>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABOVVY4LGRIM46UTGOAM6A3Y3K4ENAVCNFSM6AAAAABFSEWJ3CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMZSGE2TMMRRGM>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by jessestorbeck** [comment]
> Is there anything else?

For `pushkin`, no, but there could be branches of the various template/package repos that were ahead of the main branch when those repos were integrated into the monorepo. Assigning to @ayang21.
