### ISSUE TITLE
Quickstart: "Make sure Docker is running" for non-macOS machines

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin#38]
> Make sure Docker is running.

On macOS, this appears to be a trivial issue since a little logo appears in the menu bar. I already amended the first instance with the solutions I found for Ubuntu:

> Make sure Docker is running. On macOS, a Docker icon should show up in the menu bar at the top of the screen. On Ubuntu and WSL, you can run the command `docker info` or `sudo systemctl is-active docker` to check whether it is running. If it is not, you can run `dockerd` to start it.

Is there a better way to check whether Docker is running from the command line on macOS? If not, I will copy this explanation to the other place where it comes up.

**Comment by conbainbridge** [comment]
It looks like the command `docker info` also works for mac!
