### ISSUE TITLE
Quickstart: Does pushkin prep need to be run again after adding authentication details to config.js?

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin#39]
Does `pushkin prep` need to be run again after adding authentication details to config.js?

Further down in the document, it says:

> Every time you update code or add an experiment, you’ll need to run pushkin prep again:

If that's the case, it should be mentioned at the end of the authentication section as well.

**Comment by conbainbridge** [comment]
As far as I can tell, any edits need `pushkin prep` run to appear... @jkhartshorne ?

**Comment by jkhartshorne** [comment]
That's correct.
