### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#40]
- template section needs to be updated. the 'list' function was deprecated.
- probably need a section listing all templates, with descriptions and pointers to documentation.

**Comment by conbainbridge** [comment]
Sections with templates now exist. Maybe we can remove the rogue Template page from Getting Started altogether and add the info suggesting to update pushkin to get the latest into the Modifying Site Template and Modifying Experiment Templates pages?

**Comment by jkhartshorne** [comment]
Sounds like a plan.

**Comment by conbainbridge** [comment]
Updated!
