### ISSUE TITLE
Docs: [Getting Started] 'Deploying to AWS' has no content

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin#48]
@jkhartshorne @conbainbridge 

Is this different from testing using an Amazon EC2 instance? If not, we might be able to (1) point to those Windows setup docs or (2) reorganize to put the most general parts of running the EC2 instance here and take that out of the Windows-specific docs. If it is, then it needs to be written. @jkhartshorne, I believe you mentioned investigating Heroku instead, maybe?

**Comment by jkhartshorne** [comment]
It is different. And there's no content because I don't know what content it will have yet. My next task (starting tomorrow) is to work on deployment. Can you please add a "Coming soon!" to this part of the docs?

**Comment by parkerrobbins** [comment]
@jkhartshorne Done.

**Comment by jkhartshorne** [comment]
@parkerrobbins  Was this handled through a pull request? If so, please link the pull request (you'll see this on the right-hand sidebar) and then close the issue.

**Comment by parkerrobbins** [comment]
No, I used the dispreferred (but much faster) method of editing directly on GitBook since it was such a minor change. See commit [here](https://github.com/pushkin-consortium/pushkin/commit/15bfb2b205e5b6663e0babc1932d5206060ca080). 

I did not close the issue because I thought it would not be resolved until you had written the content for it. I will close it now.
