### ISSUE TITLE
Tutorial: Simple Experiment builds a not as powerful lexical decision exp as the new template - change this?

### ISSUE THREAD

**Issue by conbainbridge** [pushkin-consortium/pushkin#49]
Should we change this to something else I could quickly build for this? Or should we just add a comment that this is a recommended tutorial for learning the ropes, but a more complete template for lexical decisions is available (linking to the page in the docs)?

**Comment by jkhartshorne** [comment]
The latter: "this is a recommended tutorial for learning the ropes, but a more complete template for lexical decisions is available (linking to the page in the docs)"

**Comment by conbainbridge** [comment]
Added text to tutorial
