### ISSUE TITLE
Docs: [Advanced] Experiment Structure page has outdated link

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin#54]
The [Experiment Structure page](https://languagelearninglab.gitbook.io/pushkin/advanced/experiment-structure) has an outdated link.

> The CLI command [prep_](https://pushkin-social-science-at-scale.readthedocs.io/en/latest/experiments/experiment_structure.html#id2) automagically redistributes this code where it needs to go.

It isn't really clear where it's supposed to lead, but it currently leads to the same page in the old docs on ReadTheDocs.

**Comment by conbainbridge** [comment]
Updated
