### ISSUE TITLE
Docs: [Advanced] Clarify Experiment Config.yaml Files#logo-tagline-duration-other

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin#56]
[Config.yaml Files#logo-tagline-duration-other](https://languagelearninglab.gitbook.io/pushkin/advanced/experiment-structure/experiment-config-files#logo-tagline-duration-other)

> For instance, the default pushkin site template uses logo, tagline, and duration, which are self-explanatory. 

Are these self-explanatory? I don't think that they are and that explanations and examples should be given.

**Comment by conbainbridge** [comment]
Agreed and clarified!
