### ISSUE TITLE
Update npm related content with yarn versions

### ISSUE THREAD

**Issue by conbainbridge** [pushkin-consortium/pushkin#57]
I imagine this may be an extended work-in-progress, as some of the things may have changed or need to be re-tested and evaluated? These pages/sections comes to mind:
https://app.gitbook.com/@languagelearninglab/s/pushkin/advanced/testing-pushkin-with-jest
https://app.gitbook.com/@languagelearninglab/s/pushkin/developers/getting-started-on-development#testing-pushkin-modules-locally

**Comment by jkhartshorne** [comment]
@parkerrobbins - can you please try each of these with yarn and see if they can be updated?

**Comment by parkerrobbins** [comment]
Yes, I will do that.
