### ISSUE TITLE
AWS deploy: Describe anticipated cost of requirements 

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#67]
Not AWS itself, but:

- SSL certificates
- Postgres manager
- ??

**Comment by jkhartshorne** [comment]
@parkerrobbins - can you please add something about cost of domain name registration. On AWS, it currently runs around $12/yr for cheaper ones, more if you want something fancy/trendy.

**Comment by conbainbridge** [comment]
For our student workshop attendees, maybe we can recommend doing this?
https://nc.me/
