### ISSUE TITLE
Documentation for the experiment templates

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#69]
Probably should be the second section of 'Advanced', right after 'Pushkin CLI'. 

Each template should have its own section, describing how to use it.

**Comment by conbainbridge** [comment]
Moved section up, each template already has it's own page in the docs (under Modifying Experiment Templates), but I just fleshed them out to be more detailed and include a gif of the gameplay.

(See links for each exp template: https://app.gitbook.com/@languagelearninglab/s/pushkin/advanced/modifying-experiment-templates#current-templates)

**Comment by jkhartshorne** [comment]
Without looking at it carefully, I actually thought "modifying experiment templates" was a developer topic on making new templates! Maybe change it to "using experiment templates"?

**Comment by conbainbridge** [comment]
Updated
