### ISSUE TITLE
QuickStart -- what does the output look like?

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#72]
Some people are confused when there is output from a command in the command line. They think it's all errors. Including some examples for at least a few of the commands in QuickStart would probably be helpful.

But since the output can be very long, it probably should be in a scroll box. I assume this is possible in MarkDown but can't say for sure. Otherwise, maybe find some other way of shortening it or just generally making it clear that they expect output, and how to recognize an error vs. successful output.

**Comment by parkerrobbins** [comment]
@jkhartshorne So I looked into the scrollbox thing and it seems very difficult, if not impossible. Would an appropriate solution be to link to a codeblock on an unindexed page?

For example:

> See ```[here](link-to-unindexed-page)``` for sample output.
