### ISSUE TITLE
Videos for "Requirements" section of "Deploying to AWS"

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#73]
People may find it helpful to have videos like the ones we've made before for some of the more complicated parts of "Requirements". Obviously, if the video actually shows your AWS access keys, you should then immediately change them after making the video!!

Assigning both Parker and Megan, because I don't know who will have time first (this is lowest priority of the open issues). You should please coordinate amongst yourselves so that you don't end up making the same videos!

**Comment by jkhartshorne** [comment]
@parkerrobbins Are you able to work on this?

**Comment by parkerrobbins** [comment]
@jkhartshorne Let me start with converting Megan's existing videos to GIFs and including them where I can. Then, if I have time, I will create the remaining videos.

**Comment by parkerrobbins** [comment]
Just an update: It looks like there aren't existing videos for the AWS config part, so I am going through and figuring that out myself so I can make short, polished videos of each step.

**Comment by restmegan** [comment]
I finished making the AWS config videos, I noticed that the installation of the AWS CLI is different for each platform so we either need to make videos for each or not include videos of the installation

**Comment by parkerrobbins** [comment]
@jkhartshorne I think the part of the tutorial so far that most needs videos is the AWS CLI configuration. This is what Megan and I have made videos for. If you would like other videos or if there are additions to the docs that need videos, please reopen the issue.
