### ISSUE TITLE
[AWS Deployment] Is one supposed to download the AWS CLI Docker Image or the one for their OS?

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin#79]
@jkhartshorne 

A user on macOS emailed me because their installation of the AWS CLI (using the Docker image) was unsuccessful and they were not able to run `aws configure` without a `command not found` error.

So should a macOS user install [this Docker image of AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html) or the [regular CLI for macOS](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html)?

Thanks. I can clarify in the docs after I get confirmation.

**Comment by jkhartshorne** [comment]
Regular CLI for macOS.
