### ISSUE TITLE
Docs: Installing CLI globally?

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#8]
What happens if people have two versions of Pushkin? Is there a way to make CLI work only within the project root folder? 

If not, we should probably warn people...

**Comment by jkhartshorne** [comment]
Can you have multiple versions of a node packages installed globally a la python?

**Comment by jessestorbeck** [comment]
As long as we're still using Yarn Classic, users will be limited to one globally installed version of the CLI. There could be some workarounds though if a user really needed to use different versions, e.g. Codespaces, installing the CLI as a dependency of the site, or using `npx` (depending on what the user's goals were).
