### ISSUE TITLE
Add overview of different technologies and how they are used

### ISSUE THREAD

**Issue by restmegan** [pushkin-consortium/pushkin#85]

**Comment by parkerrobbins** [comment]
@jkhartshorne What would differ between that and [this](https://languagelearninglab.gitbook.io/pushkin/developers/getting-started-on-development#understanding-the-front-end)? Just something to think about.

**Comment by jkhartshorne** [comment]
@parkerrobbins -- there's a lot more. I think we'd probably also want to cover Knex, SQL, and probably a few other things.

**Comment by parkerrobbins** [comment]
@jkhartshorne Great! Should this be assigned to you since you have the most global knowledge?

**Comment by jkhartshorne** [comment]
@conbainbridge  you want to take an initial stab at this, adding things you know about?

**Comment by conbainbridge** [comment]
Here's the initial stab! I wasn't sure how deep to fall down the dependencies rabbit hole so for now I stuck to things that I had some understanding of _and_ felt might be helpful to be aware of if developing.

https://languagelearninglab.gitbook.io/pushkin/developers/overview-of-tech

**Comment by conbainbridge** [comment]
Closing for now as the list is there - of course people can and should add to it as they find more worth listing!
