### ISSUE TITLE
Docs: Local testing fails with running web server

### ISSUE THREAD

**Issue by rhancockn** [pushkin-consortium/pushkin#87]
Some people might already be running a local web server on port 80. If this is the case, the local testing section of the quickstart guide will fail with:

```
ERROR: for pushkin_server_1  Cannot start service server: Ports are not available: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for server  Cannot start service server: Ports are not available: listen tcp 0.0.0.0:80: bind: address already in use
Encountered errors while bringing up the project.
something went wrong: undefined
```

The simple solution is to try stopping the current web server with `apachectl stop`, but it would be helpful to implement/document changing the Docker port number to avoid this conflict.

**Comment by jkhartshorne** [comment]
@restmegan - add to 'troubleshooting' (unless @conbainbridge has already). For suggested solution, see https://github.com/pushkin-consortium/pushkin/discussions/97

**Comment by jkhartshorne** [comment]
@restmegan - apparently this is a reasonably common problem (see https://github.com/pushkin-consortium/pushkin/discussions/99). So in addition to adding this to troubleshooting, let's:

1. mention before running `pushkin prep` that if you're running another server (like from the Docker tutorial), be sure to close it first, and
2. briefly mention this error after immediately after the `pushkin prep` command and link to the troubleshooting response.

**Comment by conbainbridge** [comment]
Added information to the troubleshooting page of the documentation [here](https://app.gitbook.com/@languagelearninglab/s/pushkin/advanced/troubleshooting-pushkin#port-already-taken).

**Comment by jkhartshorne** [comment]
@conbainbridge -- I don't think I"m seeing this?

**Comment by conbainbridge** [comment]
Working on fixing this right now, it looks like something broke between the Gitbook GUI and Github!

**Comment by conbainbridge** [comment]
(Sorry didn't mean to close yet)
