### ISSUE TITLE
Docs: Explain YAML variables

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#9]
In "getting started", it says: "(It’s highly recommended that, when deploying any code, you refrain from typing in real passwords as plain text in the config file. Instead, use variables, which are supported by YAML.)"

Readers will need more information on how to do that. If there's already info elsewhere in the docs, link to it. If there is a good tutorial online, link to that. Otherwise, write something.

**Comment by jessestorbeck** [comment]
Docs no longer mention using variables in the config file.

**Comment by jkhartshorne** [comment]
@jessestorbeck -- are we sure that they shouldn't mention Yaml variables?
